// <auto-generated />
using System;
using HotelBookingEngineDashboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingEngineDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527182806_AddMoreHotels")]
    partial class AddMoreHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBookingEngineDashboard.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            City = "Mumbai",
                            Description = "Luxury hotel in the heart of Mumbai.",
                            IsAvailable = true,
                            Name = "The Grand Oberoi",
                            PricePerNight = 12000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 2,
                            City = "Pune",
                            Description = "Modern business hotel in Pune.",
                            IsAvailable = true,
                            Name = "Lemon Tree Premier",
                            PricePerNight = 5500m,
                            StarRating = 4
                        },
                        new
                        {
                            HotelId = 3,
                            City = "Udaipur",
                            Description = "Iconic heritage palace on Lake Pichola.",
                            IsAvailable = true,
                            Name = "Taj Lake Palace",
                            PricePerNight = 25000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 4,
                            City = "Bangalore",
                            Description = "Affordable comfort near tech parks.",
                            IsAvailable = true,
                            Name = "Ibis Styles",
                            PricePerNight = 3200m,
                            StarRating = 3
                        },
                        new
                        {
                            HotelId = 5,
                            City = "Mumbai",
                            Description = "Beachside hotel with sea views.",
                            IsAvailable = true,
                            Name = "Novotel Juhu Beach",
                            PricePerNight = 8500m,
                            StarRating = 4
                        },
                        new
                        {
                            HotelId = 6,
                            City = "Delhi",
                            Description = "Grand luxury hotel in New Delhi.",
                            IsAvailable = true,
                            Name = "The Lalit",
                            PricePerNight = 15000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 7,
                            City = "Chennai",
                            Description = "Iconic luxury hotel inspired by Chola architecture.",
                            IsAvailable = true,
                            Name = "ITC Grand Chola",
                            PricePerNight = 18000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 8,
                            City = "Pune",
                            Description = "Premium business hotel in Pune.",
                            IsAvailable = true,
                            Name = "Marriott",
                            PricePerNight = 9000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 9,
                            City = "Mumbai",
                            Description = "Luxury hotel with stunning city views.",
                            IsAvailable = true,
                            Name = "Hyatt Regency",
                            PricePerNight = 14000m,
                            StarRating = 5
                        },
                        new
                        {
                            HotelId = 10,
                            City = "Delhi",
                            Description = "Modern hotel near business district.",
                            IsAvailable = true,
                            Name = "Radisson Blu",
                            PricePerNight = 7500m,
                            StarRating = 4
                        },
                        new
                        {
                            HotelId = 11,
                            City = "Bangalore",
                            Description = "Comfortable stay in tech city.",
                            IsAvailable = true,
                            Name = "Fortune Select",
                            PricePerNight = 4500m,
                            StarRating = 4
                        },
                        new
                        {
                            HotelId = 12,
                            City = "Udaipur",
                            Description = "Lakeside luxury with heritage charm.",
                            IsAvailable = true,
                            Name = "Trident Hotel",
                            PricePerNight = 20000m,
                            StarRating = 5
                        });
                });

            modelBuilder.Entity("HotelBookingEngineDashboard.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestAge")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelBookingEngineDashboard.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelBookingEngineDashboard.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("HotelBookingEngineDashboard.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBookingEngineDashboard.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingEngineDashboard.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
